name: 🐞 Issue report
description: Report an issue with a provider
labels: [ bug ]
body:

  -   type: input
      id: provider
      attributes:
        label: Provider information
        description: |
          You can find the provider name in the provider screen.
        placeholder: |
          Example: "Stremio"
      validations:
        required: true

  -   type: textarea
      id: reproduce-steps
      attributes:
        label: Steps to reproduce
        description: Provide an example of the issue.
        placeholder: |
          Example:
            1. First step
            2. Second step
            3. Issue here
      validations:
        required: false

  -   type: input
      id: flixclusive-version
      attributes:
        label: Flixclusive version
        description: |
          You can find your Flixclusive version in **Settings**.
        placeholder: |
          Example: "2.0.0"
      validations:
        required: true

  -   type: textarea
      id: other-details
      attributes:
        label: Other details
        placeholder: |
          Additional details and attachments.

  -   type: checkboxes
      id: acknowledgements
      attributes:
        label: Acknowledgements
        options:
          -   label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
              required: true