name: ⭐ Provider request
description: Suggest a provider that you would like to be added
labels: [ provider request ]
body:

  -   type: input
      id: provider-name
      attributes:
        label: Provider name
        description: |
          Provide the provider name.
        placeholder: |
          Example: "Kitsu"
      validations:
        required: true

  -   type: input
      id: provider-url
      attributes:
        label: Provider URL
        description: |
          Provide the provider URL.
        placeholder: |
          Example: "https://kitsu.io"
      validations:
        required: true

  -   type: input
      id: package-type
      attributes:
        label: Package type
        placeholder: |
          Example: "anime catalogs"
      validations:
        required: false

  -   type: input
      id: language
      attributes:
        label: Provider language
        placeholder: |
          Example: "en"
      validations:
        required: false

  -   type: textarea
      id: other-details
      attributes:
        label: Other details
        placeholder: |
          Additional details and attachments.

  -   type: checkboxes
      id: acknowledgements
      attributes:
        label: Acknowledgements
        options:
          -   label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
              required: true