name: Generate README

concurrency:
  group: "Generate README"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Update README.md with library statuses
        run: |
          chmod +x .github/generate_readme.sh
          .github/generate_readme.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: |
            docs: update README [skip ci]
          title: Providers status update