name: PR Build Check

concurrency:
  group: "build pull request"
  cancel-in-progress: true

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: "src"

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Change `**/**/build/*.flx` if you've changed the providers file structure.
      - name: Build providers
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make generateUpdaterJson